### ISSUE TITLE
Error: Cannot find module 'archiver'

### ISSUE THREAD

**Issue by Go2Engle** [uldiseihenbergs/meshcentral-builds#3]
Just started the other day im getting the bellow error. Any ideas?

```Installing archiver@4.0.2...
Installing nodemailer...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.87, WAN mode.
ERR: module.js:549
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43)
    at emitNone (events.js:106:13)
    at Duplex.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at afterWrite (_stream_writable.js:465:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
{ Error: Command failed: /usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7
module.js:549
    throw err;
    ^


Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43)
    at emitNone (events.js:106:13)
    at Duplex.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at afterWrite (_stream_writable.js:465:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7' }
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...```

**Comment by uldiseihenbergs** [comment]
hello! can you provide full log?
mine looks like this:
``Installing archiver@4.0.2...
Installing otplib@10.2.3...
Installing archiver@4.0.2...
MeshCentral HTTP redirection server running on port 80.
MeshCentral v0.7.87, WAN mode.
``

**Comment by Go2Engle** [comment]
@uldiseihenbergs would you like the full docker log or the meshcentral log?

**Comment by uldiseihenbergs** [comment]
docker log.

**Comment by Go2Engle** [comment]
attached is the full log. Deleted and recreated the container for fresh log.
```Installing archiver@4.0.2...,
Installing nodemailer...,
Installing otplib@10.2.3...,
Installing archiver@4.0.2...,
Installing nodemailer...,
MeshCentral HTTP redirection server running on port 80.,
MeshCentral v0.7.87, WAN mode.,
ERR: module.js:549,
    throw err;,
    ^,
,
Error: Cannot find module 'archiver',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Module.require (module.js:596:17),
    at require (internal/module.js:11:18),
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43),
    at emitNone (events.js:106:13),
    at Duplex.emit (events.js:208:7),
    at finishMaybe (_stream_writable.js:614:14),
    at afterWrite (_stream_writable.js:465:3),
    at _combinedTickCallback (internal/process/next_tick.js:144:20),
{ Error: Command failed: /usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7,
module.js:549,
    throw err;,
    ^,
,
Error: Cannot find module 'archiver',
    at Function.Module._resolveFilename (module.js:547:15),
    at Function.Module._load (module.js:474:25),
    at Module.require (module.js:596:17),
    at require (internal/module.js:11:18),
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43),
    at emitNone (events.js:106:13),
    at Duplex.emit (events.js:208:7),
    at finishMaybe (_stream_writable.js:614:14),
    at afterWrite (_stream_writable.js:465:3),
    at _combinedTickCallback (internal/process/next_tick.js:144:20),
,
    at ChildProcess.exithandler (child_process.js:275:12),
    at emitTwo (events.js:131:20),
    at ChildProcess.emit (events.js:214:7),
    at maybeClose (internal/child_process.js:925:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5),
  killed: false,,
  code: 1,,
  signal: null,,
  cmd: '/usr/local/bin/node /home/node/meshcentral/node_modules/meshcentral/meshcentral.js --launch 7' },
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...,```

**Comment by Go2Engle** [comment]
when i open my mesherrors.txt file i see the similar error. goes back to the 14th it looks like.

```-------- 2021-3-14 05:03:25 ---- 0.7.87 --------

module.js:549
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Duplex.<anonymous> (/home/node/meshcentral/node_modules/meshcentral/meshcentral.js:2546:43)
    at emitNone (events.js:106:13)
    at Duplex.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at afterWrite (_stream_writable.js:465:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
```

**Comment by Go2Engle** [comment]
Another update. i rolled back and used container tag 0.7.72 and its working. seems to be just an issue with the latest version for me.

**Comment by uldiseihenbergs** [comment]
ok, i cross posted this to meshcentral issue list..

**Comment by Go2Engle** [comment]
just seen that! thanks! was browsing and possibly related to this? https://github.com/Ylianst/MeshCentral/issues/2388
looks like he pushed 0.7.88 to fix some issues. Maybe 0.7.88 would do the trick?

**Comment by uldiseihenbergs** [comment]
Don't know, but i can rebuild the latest tag.

**Comment by uldiseihenbergs** [comment]
latest tag updated to 0.7.89 now. please try and report back..

**Comment by Go2Engle** [comment]
awesome that did the trick! thank you!
